# Generated by Django 6.0.3 on 2026-07-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='fb',
            field=models.CharField(max_length=50),
        ),
    ]
